# Generated by Django 3.0.7 on 2020-06-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20200623_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='url',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
