# Generated by Django 3.0.7 on 2020-06-23 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_persona_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='url',
        ),
    ]
